import { useMemo, useState } from "react";
import { buildAgendaLayout, minuteLabel } from "@/lib/agendaLayout";
import { useRouter } from "@/context/useRouter";
import { Card } from "@/components/ui/Card";
import { Input, Select } from "@/components/ui/Field";
import type { Session } from "@/types";

export function AgendaView({ sessions }: { sessions: Session[] }) {
  const { navigate }=useRouter();
  const [query,setQuery]=useState(""); const [tag,setTag]=useState(""); const [room,setRoom]=useState(""); const [level,setLevel]=useState(""); const [view,setView]=useState("grid");
  const filtered=useMemo(()=>sessions.filter((session)=> (!tag || session.tags?.includes(tag)) && (!room || session.room===room) && (!level || session.difficulty===level) && (!query.trim() || [session.title,session.speaker?.full_name,session.description].some((value)=>value?.toLowerCase().includes(query.trim().toLowerCase())))),[sessions,query,tag,room,level]);
  const days=useMemo(()=>{
    const multiple=new Set(filtered.map((session)=>session.conference_id)).size>1;
    return buildAgendaLayout(multiple ? filtered.map((session)=>({...session,room:`${session.conference?.title || session.conference_id} · ${session.room || "Chưa phân phòng"}`})):filtered);
  },[filtered]);
  const tags=[...new Set(sessions.flatMap((session)=>session.tags ?? []))].sort();
  return <div className="space-y-4">
    <Card className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4"><Input label="Tìm phiên / diễn giả" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Tên phiên hoặc diễn giả" /><Select label="Chủ đề" value={tag} onChange={(event)=>setTag(event.target.value)}><option value="">Tất cả chủ đề</option>{tags.map((tag)=><option key={tag}>{tag}</option>)}</Select><Select label="Phòng" value={room} onChange={(event)=>setRoom(event.target.value)}><option value="">Tất cả phòng</option>{[...new Set(sessions.map((s)=>s.room).filter(Boolean))].map((room)=><option key={room}>{room}</option>)}</Select><Select label="Mức độ (workshop)" value={level} onChange={(event)=>setLevel(event.target.value)}><option value="">Tất cả mức độ</option><option value="general">Chung</option><option value="beginner">Cơ bản</option><option value="advanced">Nâng cao</option></Select></Card>
    <div className="flex items-center justify-between"><p className="text-sm text-slate-500">{filtered.length} phiên phù hợp · Chọn phiên để xem tài liệu và điểm danh</p><div className="hidden gap-2 lg:flex">{[["grid","Lưới thời gian"],["list","Danh sách"]].map(([key,label])=><button key={key} type="button" aria-pressed={view===key} onClick={()=>setView(key)} className={`rounded-lg px-3 py-2 text-sm ${view===key ? "bg-teal-700 text-white" : "bg-white text-slate-600"}`}>{label}</button>)}</div></div>
    {!filtered.length && <Card className="p-8 text-center text-slate-500">Không có phiên phù hợp với bộ lọc.</Card>}
    <div className={view==="grid" ? "space-y-3 lg:hidden" : "space-y-3"}>{filtered.map((session)=><button key={session.id} className="block w-full rounded-xl border border-slate-200 bg-white p-4 text-left hover:border-teal-500" onClick={()=>navigate("session-detail",{id:session.id})}><p className="text-xs font-medium text-teal-700">{new Date(session.start_time).toLocaleString("vi-VN")} – {new Date(session.end_time).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})}</p><h3 className="mt-2 font-semibold">{session.title}</h3><p className="mt-1 text-sm text-slate-500">{session.room || "Chưa phân phòng"} · {session.speaker?.full_name || "Chưa xác định diễn giả"}</p>{session.tags?.length ? <p className="mt-2 text-xs text-teal-700">{session.tags.join(" · ")}</p>:null}</button>)}</div>
    {view==="grid" && <div className="hidden space-y-5 lg:block">{days.map((day)=><Card key={day.date} className="overflow-hidden"><h3 className="border-b border-slate-200 p-4 font-semibold">{new Date(day.date+"T12:00:00").toLocaleDateString("vi-VN")}</h3><div className="max-h-[680px] overflow-auto"><div style={{minWidth:90+day.rooms.length*260}}><div className="sticky top-0 z-20 grid border-b border-slate-200 bg-white" style={{gridTemplateColumns:`90px repeat(${day.rooms.length},1fr)`}}><div className="p-3 text-sm font-medium">Giờ</div>{day.rooms.map((room)=><div key={room} className="border-l border-slate-200 p-3 text-sm font-semibold text-teal-800">{room}</div>)}</div><div className="grid" style={{gridTemplateColumns:`90px repeat(${day.rooms.length},1fr)`}}><div className="relative bg-slate-50" style={{height:(day.end-day.start)*2}}>{Array.from({length:(day.end-day.start)/30},(_,i)=><div key={i} className="absolute w-full border-t border-slate-200 px-2 text-xs text-slate-500" style={{top:i*60}}>{minuteLabel(day.start+i*30)}</div>)}</div>{day.rooms.map((room)=><div key={room} className="relative border-l border-slate-200" style={{height:(day.end-day.start)*2,backgroundImage:"repeating-linear-gradient(to bottom,transparent 0,transparent 59px,#e2e8f0 59px,#e2e8f0 60px)"}}>{day.slots.filter((slot)=>slot.room===room).map((slot)=><button key={slot.session.id} onClick={()=>navigate("session-detail",{id:slot.session.id})} className={`absolute overflow-auto rounded-lg border p-2 text-left shadow-sm hover:ring-2 hover:ring-teal-500 ${slot.session.parent_session_id ? "border-teal-200 bg-teal-50" : "border-blue-200 bg-blue-50"}`} style={{top:(slot.start-day.start)*2,height:Math.max(32,(slot.end-slot.start)*2-4),left:`${slot.lane*100/slot.lanes}%`,width:`calc(${100/slot.lanes}% - 4px)`}}><p className="text-[11px] font-medium text-teal-700">{minuteLabel(slot.start)}–{minuteLabel(slot.end)}</p><p className="mt-1 text-sm font-semibold">{slot.session.title}</p><p className="mt-1 text-xs text-slate-600">{slot.session.speaker?.full_name}</p></button>)}</div>)}</div></div></div></Card>)}</div>}
  </div>;
}
